//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Domain : global::System.Configuration.ApplicationSettingsBase {
        
        private static Domain defaultInstance = ((Domain)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Domain())));
        
        public static Domain Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BLOGTRUYEN {
            get {
                return ((string)(this["BLOGTRUYEN"]));
            }
            set {
                this["BLOGTRUYEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TRUYENTRANH8 {
            get {
                return ((string)(this["TRUYENTRANH8"]));
            }
            set {
                this["TRUYENTRANH8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TRUYENTRANHTUAN {
            get {
                return ((string)(this["TRUYENTRANHTUAN"]));
            }
            set {
                this["TRUYENTRANHTUAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HOCVIENTRUYENTRANH {
            get {
                return ((string)(this["HOCVIENTRUYENTRANH"]));
            }
            set {
                this["HOCVIENTRUYENTRANH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IZTRUYENTRANH {
            get {
                return ((string)(this["IZTRUYENTRANH"]));
            }
            set {
                this["IZTRUYENTRANH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LHMANGA {
            get {
                return ((string)(this["LHMANGA"]));
            }
            set {
                this["LHMANGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TRUYENTRANHNET {
            get {
                return ((string)(this["TRUYENTRANHNET"]));
            }
            set {
                this["TRUYENTRANHNET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TRUYENTRANHMOI {
            get {
                return ((string)(this["TRUYENTRANHMOI"]));
            }
            set {
                this["TRUYENTRANHMOI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MANGAK {
            get {
                return ((string)(this["MANGAK"]));
            }
            set {
                this["MANGAK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UPTRUYEN {
            get {
                return ((string)(this["UPTRUYEN"]));
            }
            set {
                this["UPTRUYEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MANGAFOX {
            get {
                return ((string)(this["MANGAFOX"]));
            }
            set {
                this["MANGAFOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KISSMANGA {
            get {
                return ((string)(this["KISSMANGA"]));
            }
            set {
                this["KISSMANGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MANGAPARK {
            get {
                return ((string)(this["MANGAPARK"]));
            }
            set {
                this["MANGAPARK"] = value;
            }
        }
    }
}
